### ISSUE TITLE
出现cross-origin data异常

### ISSUE THREAD

**Issue by YeomanYe** [BUPT-HJM/BoomGo#1]
在调用getImageData时报错,the canvas has tainted by cross-origin data
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BoomTest</title>
    <link rel="stylesheet" href="css/boom.css" type="text/css">
    <script src="js/jquery-3.0.0.js" type="text/javascript"></script>
    <script src="js/boom.js" type="text/javascript"></script>
</head>
<body>
    <canvas id="canvas1" width="800" height="600"></canvas>
    <script>
        $(function(){
            boom("canvas1","rest.png").go(3000);    
        });
    </script>
</body>
</html>`

**Comment by BUPT-HJM** [comment]
chrome的本地文件限制
方法一： 起一个服务器，localhost访问
方法二： 右键chrome属性，在目标里加上空格，再加`--allow-file-access-from-files`
类似这样`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files`

**Comment by YeomanYe** [comment]
@BUPT-HJM
用方法二解决了问题
