### ISSUE TITLE
Line 175 bug,导致某些尺寸图片死循环

### ISSUE THREAD

**Issue by GESTAR** [BUPT-HJM/BoomGo#2]
Line 175 bug,导致某些尺寸图片死循环，ex:362 × 682

去掉这个判断就好了

**Comment by BUPT-HJM** [comment]
谢谢提出bug,由于前几天邮箱邮件过多没看到没有及时回复表示歉意

bug已解决,这句话是为了提升性能,超出范围部分小球不再更新位置,误将`height`写成`width`导致这个问题
